<?php

########################################################################
# Extension Manager/Repository config file for ext: "media_gallery"
#
# Auto generated by Extension Builder 2011-10-20
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Media Gallery',
	'description' => 'Media gallery frontend plugin extension.',
	'category' => 'plugin',
	'author' => 'Ingmar Schlecht',
	'author_email' => 'ingmar@typo3.org',
	'author_company' => 'TYPO3 Association',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'media' => ''
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>